### ISSUE TITLE
Which Whycon?

### ISSUE THREAD

**Issue by raultron** [LCAS/whycon#3]
Hi,
I used Whycon a long time ago in a dynamic fiducial marker (https://ieeexplore.ieee.org/document/8588599). Now I am working on an improved version of that system, and I want to integrate Whycon, but I am baffled about which repository to use now (I am in ROS melodic).

I would like to track at least one marker simultaneously without the new ID ring on the inside of the marker, and I would like a version that publishes the detected marker in ROS topics, I don't need any GUI.

Thanks!

**Comment by pet1330** [comment]
Hi,

Yes, we are working on consolidating all of the different version of WhyCon. Unfortunately, there are quite a few variances which are all slightly different and as such, it is difficult to find the time to actually do this. But we are hoping to get this sorted soon :crossed_fingers:

The most up to date version for ROS Melodic is the default branch [snapcart](https://github.com/LCAS/whycon/tree/snapcart). The ID encoding is completely optional, you can disable it in the [config file](https://github.com/LCAS/whycon/blob/964f17746041329415112ff312e1967fa64c6de2/cfg/whycon.cfg#L8)

Hope this helps :smiley:
