### ISSUE TITLE
Unable to get correct IDs

### ISSUE THREAD

**Issue by kumarkamit** [LCAS/whycon#6]
I tried to implement this on my laptop using Ubuntu 20.04 & ROS Noetic. However, the IDs keep on fluctuating randomly when we change the yaw of the marker.

The diameter of the marker and hamming distance are kept the same as required.

Could you tell me where I am going wrong?

**Comment by nikostsagk** [comment]
Indeed the markers do not keep their ID during rotations, however they still stay **unique**.

E.g. marker A can get only {1,3,8} as possible IDs during rotation while marker B can get only {2,5,9} etc. Having a dictionary helped me.

Have a look on this as well: https://github.com/jiriUlr/whycode-gen

**Comment by kumarkamit** [comment]
Great. Thank you.
